const express = require("express");
const router = express.Router();
router.use("/auth", require("./auth.routes"));
router.use("/functions", require("./functions.routes"));
router.use("/badge", require("./badge.routes"));
router.use("/chatconversation", require("./chatconversation.routes"));
router.use("/chatmessage", require("./chatmessage.routes"));
router.use("/course", require("./course.routes"));
router.use("/courselevel", require("./courselevel.routes"));
router.use("/enrollment", require("./enrollment.routes"));
router.use("/exercise", require("./exercise.routes"));
router.use("/exerciseattempt", require("./exerciseattempt.routes"));
router.use("/flashcard", require("./flashcard.routes"));
router.use("/instructorprofile", require("./instructorprofile.routes"));
router.use("/instructorrating", require("./instructorrating.routes"));
router.use("/instructorwallet", require("./instructorwallet.routes"));
router.use("/instructorwallettransaction", require("./instructorwallettransaction.routes"));
router.use("/integration", require("./integration.routes"));
router.use("/Language", require("./language.routes"));
router.use("/lesson", require("./lesson.routes"));
router.use("/message", require("./message.routes"));
router.use("/notification", require("./notification.routes"));
router.use("/quiz", require("./quiz.routes"));
router.use("/quizattempt", require("./quizattempt.routes"));
router.use("/review", require("./review.routes"));
router.use("/studentcourselevelprogress", require("./studentcourselevelprogress.routes"));
router.use("/studentmaterialbookmark", require("./studentmaterialbookmark.routes"));
router.use("/studymaterial", require("./studymaterial.routes"));
router.use("/teachingsession", require("./teachingsession.routes"));
router.use("/userbadge", require("./userbadge.routes"));
router.use("/userpoints", require("./userpoints.routes"));
router.use("/wallet", require("./wallet.routes"));
router.use("/razorpay", require("./razorpay.routes"));
router.use("/aggregate", require("./aggregate"));
router.use('/User',require('./user.route'))
module.exports = router;
