require("dotenv-flow").config();
module.exports = {
  env: {
    NODE_ENV: process.env.NODE_ENV,
    JWT_SECRET: process.env.JWT_SECRET,
    OPENAI_KEY: process.env.OPENAI_KEY,
    JWT_ACCESS_TOKEN_VALIDITY: process.env.JWT_ACCESS_TOKEN_VALIDITY,
    DB_PASSWORD: process.env.DB_PASSWORD,
    DB_NAME: process.env.DB_NAME,
    DB_USER: process.env.DB_USER,
    DB_URL: process.env.DB_URL,
    FB_CLIENT_ID: process.env.FB_CLIENT_ID,
    FB_CLIENT_SECRET: process.env.FB_CLIENT_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GMAIL_USERNAME: process.env.GMAIL_USERNAME,
    GMAIL_PASSWORD: process.env.GMAIL_PASSWORD,
    OTP_GMAIL_USERNAME: process.env.OTP_GMAIL_USERNAME,
    OTP_GMAIL_PASSWORD: process.env.OTP_GMAIL_PASSWORD,
    EMAIL_HOST: process.env.EMAIL_HOST,
    EMAIL_PORT: process.env.EMAIL_PORT,
    LINK: process.env.LINK,
    S3_accessKeyId: process.env.S3_accessKeyId,
    S3_secretAccessKey: process.env.S3_secretAccessKey,
    S3_BucketName: process.env.S3_BucketName,
    S3_Region: process.env.S3_Region,
    firebaseAdmin: {
      type: process.env.FIREBASE_type,
      project_id: process.env.FIREBASE_project_id,
      private_key_id: process.env.FIREBASE_private_key_id,
      private_key: process.env.FIREBASE_private_key?.replace(/\\n/g, '\n'),
      client_email: process.env.FIREBASE_client_email,
      client_id: process.env.FIREBASE_client_id,
      auth_uri: process.env.FIREBASE_auth_uri,
      token_uri: process.env.FIREBASE_token_uri,
      auth_provider_x509_cert_url: process.env.FIREBASE_auth_provider_x509_cert_url,
      client_x509_cert_url: process.env.FIREBASE_client_x509_cert_url,
      universe_domain: process.env.FIREBASE_universe_domain
    },
    OpenAImodelname: process.env.OPEN_AI_MODEL,
    colors: ['#AF94E9', '#57B8FF', '#EC9734', '#67DC71', '#FF5A5A', '#DE77DB'],
  },
};
